name: Deploy to S3

on:
  push:
    branches: [ main ] # Change to your main branch name (master/main)
    paths:
      - 'apps/frontend/**' # Only trigger on changes in the frontend app
      - '.github/workflows/deploy.yml' # Trigger on workflow file changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0 # Use your project's Node version

      - name: Install dependencies
        run: |
          cd apps/frontend
          npm install

      - name: Build project
        run: |
          cd apps/frontend
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync ./apps/frontend/dist s3://${{ secrets.AWS_S3_BUCKET }} \
          --delete
          
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"
